"""Type stubs for the compiled extension module."""

from __future__ import annotations

import enum
from typing import List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

__version__: str

class Rate(enum.Enum):
    IMBE_7200X4400 = ...
    IMBE_4400X4400 = ...
    AMBEPLUS2_3600X2450 = ...
    AMBEPLUS2_2450X2450 = ...

    fec_frame_bytes: int

    def erasure_frame(self) -> bytes: ...

class EnhancementMode(enum.Enum):
    NONE = ...
    CLASSICAL = ...

class Vocoder:
    rate: Rate
    frame_samples: int
    fec_frame_bytes: int

    # Encoder toggles. blip25-mbe 0.3.0 is a pure bits-in/bits-out codec;
    # the only two runtime toggles are tone detection and the post-decode
    # enhancement mode.
    tone_detection: bool
    enhancement: EnhancementMode

    # One wire frame marked as an erasure, to substitute for a frame the
    # transport lost. Same value as `vocoder.rate.erasure_frame()`.
    erasure_frame: bytes

    def __init__(self, rate: Rate) -> None: ...
    def encode_pcm(self, pcm: NDArray[np.int16]) -> bytes: ...
    def decode_bits(self, bits: bytes) -> NDArray[np.int16]: ...
    def reset(self) -> None: ...

    def set_tone_detection(self, on: bool) -> None: ...
    def set_enhancement(self, mode: EnhancementMode) -> None: ...

    def last_output_kind(self) -> Optional[str]: ...
    def last_tone_detection(self) -> Optional[Tuple[int, int]]: ...

    # "use" | "repeat" | "mute" | "silence" — anything but "use" means the
    # audio just returned is not what the sender encoded.
    def last_disposition(self) -> Optional[str]: ...
    def last_decode_errors(self) -> Optional[Tuple[int, int]]: ...

class LiveEncoder:
    rate: Rate
    pending_samples: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, pcm: NDArray[np.int16]) -> List[bytes]: ...
    def flush(self) -> List[bytes]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class LiveDecoder:
    rate: Rate
    pending_bytes: int

    def __init__(self, rate: Rate) -> None: ...
    def push(self, bits: bytes) -> List[NDArray[np.int16]]: ...
    def discard_pending(self) -> None: ...
    def reset(self) -> None: ...

class Transcoder:
    def __init__(self, src: Rate, dst: Rate) -> None: ...
    def transcode(self, bits: bytes) -> bytes: ...
    def reset(self) -> None: ...
